# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'template.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHBoxLayout,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QPushButton, QRadioButton, QSizePolicy, QSpinBox,
    QTabWidget, QTextEdit, QWidget)

class Ui_Frame(object):
    def setupUi(self, Frame):
        if not Frame.objectName():
            Frame.setObjectName(u"Frame")
        Frame.resize(674, 439)
        font = QFont()
        font.setFamilies([u".AppleSystemUIFont"])
        Frame.setFont(font)
        self.listWidget = QListWidget(Frame)
        QListWidgetItem(self.listWidget)
        QListWidgetItem(self.listWidget)
        QListWidgetItem(self.listWidget)
        QListWidgetItem(self.listWidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(20, 110, 181, 261))
        self.listWidget.setFont(font)
        self.label = QLabel(Frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 101, 31))
        font1 = QFont()
        font1.setFamilies([u".AppleSystemUIFont"])
        font1.setPointSize(18)
        self.label.setFont(font1)
        self.label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.open = QPushButton(Frame)
        self.open.setObjectName(u"open")
        self.open.setGeometry(QRect(110, 20, 100, 32))
        self.open.setFont(font)
        icon = QIcon(QIcon.fromTheme(u"folder-new"))
        self.open.setIcon(icon)
        self.save = QPushButton(Frame)
        self.save.setObjectName(u"save")
        self.save.setGeometry(QRect(220, 20, 100, 32))
        self.save.setFont(font)
        icon1 = QIcon(QIcon.fromTheme(u"document-save"))
        self.save.setIcon(icon1)
        self.duplicate = QPushButton(Frame)
        self.duplicate.setObjectName(u"duplicate")
        self.duplicate.setGeometry(QRect(330, 20, 100, 32))
        self.duplicate.setFont(font)
        icon2 = QIcon(QIcon.fromTheme(u"edit-copy"))
        self.duplicate.setIcon(icon2)
        self.delete_2 = QPushButton(Frame)
        self.delete_2.setObjectName(u"delete_2")
        self.delete_2.setGeometry(QRect(440, 20, 100, 32))
        self.delete_2.setFont(font)
        icon3 = QIcon(QIcon.fromTheme(u"edit-clear"))
        self.delete_2.setIcon(icon3)
        self.label_2 = QLabel(Frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 90, 41, 21))
        font2 = QFont()
        font2.setFamilies([u".AppleSystemUIFont"])
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setItalic(False)
        self.label_2.setFont(font2)
        self.tabWidget = QTabWidget(Frame)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(210, 110, 281, 261))
        self.tabWidget.setFont(font)
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_4 = QLabel(self.tab_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 81, 16))
        font3 = QFont()
        font3.setFamilies([u".AppleSystemUIFont"])
        font3.setBold(True)
        self.label_4.setFont(font3)
        self.class_2 = QComboBox(self.tab_5)
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.addItem("")
        self.class_2.setObjectName(u"class_2")
        self.class_2.setGeometry(QRect(130, 30, 101, 41))
        self.label_5 = QLabel(self.tab_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(90, 40, 41, 16))
        self.label_5.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_6 = QLabel(self.tab_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(70, 70, 61, 20))
        self.label_6.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.surname = QLineEdit(self.tab_5)
        self.surname.setObjectName(u"surname")
        self.surname.setGeometry(QRect(142, 70, 81, 21))
        self.label_7 = QLabel(self.tab_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(100, 100, 31, 20))
        self.label_7.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.name = QLineEdit(self.tab_5)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(142, 100, 81, 21))
        self.label_8 = QLabel(self.tab_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 130, 41, 16))
        self.g1 = QRadioButton(self.tab_5)
        self.g1.setObjectName(u"g1")
        self.g1.setGeometry(QRect(140, 130, 41, 20))
        self.g2 = QRadioButton(self.tab_5)
        self.g2.setObjectName(u"g2")
        self.g2.setGeometry(QRect(180, 130, 41, 20))
        self.station = QSpinBox(self.tab_5)
        self.station.setObjectName(u"station")
        self.station.setGeometry(QRect(140, 160, 101, 22))
        self.label_9 = QLabel(self.tab_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(60, 160, 71, 20))
        self.label_10 = QLabel(self.tab_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(90, 190, 41, 16))
        self.suggetions = QLineEdit(self.tab_5)
        self.suggetions.setObjectName(u"suggetions")
        self.suggetions.setGeometry(QRect(140, 190, 81, 21))
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.textEdit = QTextEdit(self.tab_6)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 40, 251, 181))
        self.label_3 = QLabel(self.tab_6)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 81, 16))
        self.label_3.setFont(font3)
        self.tabWidget.addTab(self.tab_6, "")
        self.widget = QWidget(Frame)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(500, 120, 161, 251))
        self.label_13 = QLabel(self.widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 0, 58, 16))
        font4 = QFont()
        font4.setFamilies([u".AppleSystemUIFont"])
        font4.setPointSize(16)
        self.label_13.setFont(font4)
        self.horizontalLayoutWidget = QWidget(Frame)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(19, 380, 371, 51))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_12 = QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName(u"label_12")
        font5 = QFont()
        font5.setFamilies([u".AppleSystemUIFont"])
        font5.setPointSize(14)
        self.label_12.setFont(font5)
        self.label_12.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.label_12)

        self.label_11 = QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setFont(font5)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.label_11)


        self.retranslateUi(Frame)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Frame)
    # setupUi

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QCoreApplication.translate("Frame", u"Frame", None))

        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        ___qlistwidgetitem = self.listWidget.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("Frame", u"wpis1", None));
        ___qlistwidgetitem1 = self.listWidget.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("Frame", u"wpis2", None));
        ___qlistwidgetitem2 = self.listWidget.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("Frame", u"wpis3", None));
        ___qlistwidgetitem3 = self.listWidget.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("Frame", u"wpis4", None));
        self.listWidget.setSortingEnabled(__sortingEnabled)

        self.label.setText(QCoreApplication.translate("Frame", u"Narz\u0119dzia:", None))
        self.open.setText(QCoreApplication.translate("Frame", u"Otw\u00f3rz", None))
        self.save.setText(QCoreApplication.translate("Frame", u"Zapisz", None))
        self.duplicate.setText(QCoreApplication.translate("Frame", u"Duplikuj", None))
        self.delete_2.setText(QCoreApplication.translate("Frame", u"Usu\u0144", None))
        self.label_2.setText(QCoreApplication.translate("Frame", u"Lista:", None))
        self.label_4.setText(QCoreApplication.translate("Frame", u"Formularz:", None))
        self.class_2.setItemText(0, QCoreApplication.translate("Frame", u"4a", None))
        self.class_2.setItemText(1, QCoreApplication.translate("Frame", u"4b", None))
        self.class_2.setItemText(2, QCoreApplication.translate("Frame", u"4c", None))
        self.class_2.setItemText(3, QCoreApplication.translate("Frame", u"4d", None))

        self.label_5.setText(QCoreApplication.translate("Frame", u"Klasy", None))
        self.label_6.setText(QCoreApplication.translate("Frame", u"Nazwisko", None))
        self.label_7.setText(QCoreApplication.translate("Frame", u"Imie", None))
        self.label_8.setText(QCoreApplication.translate("Frame", u"Grupa", None))
        self.g1.setText(QCoreApplication.translate("Frame", u"g1", None))
        self.g2.setText(QCoreApplication.translate("Frame", u"g2", None))
        self.label_9.setText(QCoreApplication.translate("Frame", u"Stanowisko", None))
        self.label_10.setText(QCoreApplication.translate("Frame", u"Uwagi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Frame", u"Edytor", None))
        self.label_3.setText(QCoreApplication.translate("Frame", u"Formularz:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("Frame", u"TextArea", None))
        self.label_13.setText(QCoreApplication.translate("Frame", u"Pomoc", None))
        self.label_12.setText(QCoreApplication.translate("Frame", u"Status: zlicz wpisy", None))
        self.label_11.setText(QCoreApplication.translate("Frame", u"Status: zapisano", None))
    # retranslateUi

