# Generated by Django 5.1.1 on 2024-09-13 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=10)),
                ('wychowawca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wychowawca_klasy', to='librusApp.nauczyciel')),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('nauczyciel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librusApp.nauczyciel')),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librusApp.klasa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.CharField(choices=[('1', 'Niedostateczny'), ('2', 'Dopuszczający'), ('3', 'Dostateczny'), ('4', 'Dobry'), ('5', 'Bardzo dobry'), ('6', 'Celujący')], max_length=1)),
                ('data_wystawienia', models.DateField(auto_now_add=True)),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librusApp.przedmiot')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librusApp.uczen')),
            ],
        ),
        migrations.CreateModel(
            name='UczenPrzedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisu', models.DateField(auto_now_add=True)),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librusApp.przedmiot')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librusApp.uczen')),
            ],
            options={
                'unique_together': {('uczen', 'przedmiot')},
            },
        ),
    ]
